name: CI/CD Pipeline

on:
  push:
    branches:
      - dev   # Körs när det görs en push till dev-grenen
  pull_request:
    branches:
      - main  # Körs när en pull request görs mot main-grenen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Steg 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Steg 2: Setup .NET 9.0
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      # Steg 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Steg 4: Build project
      - name: Build project
        run: dotnet build --configuration Release

      # Steg 5: Run tests
      - name: Run Tests
        run: dotnet test --configuration Release

      # Steg 6: Publish application
      - name: Publish Application
        run: dotnet publish -c Release -o ./publish

      # Steg 7: Zip published files
      - name: Zip published files
        run: |
          cd publish
          zip -r ../site.zip ./*
          cd ..

      # Steg 8: Deploy to AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        uses: aws-actions/aws-elastic-beanstalk-deploy@v1
        with:
          application-name: cicdAPI           # Här använder vi det specifika namn du gav
          environment-name: CicdAPI-env      # Här använder vi det specifika namn du gav
          version-label: ${{ github.run_id }}
          region: eu-north-1
          deployment-package: site.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
