name: Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🛒 Check out repository
      uses: actions/checkout@v3

    - name: 🏗️ Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: 🔧 Restore dependencies
      run: dotnet restore

    - name: 🔬 Run tests
      run: dotnet test --configuration Release --no-build

    - name: 🏗️ Build project
      run: dotnet publish -c Release -f net9.0 -o site

    - name: 📦 Create zip package
      run: |
        cd site
        zip -r ../site.zip .

    - name: 🔑 Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: 🚀 Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Cicd
        environment_name: Cicd-env
        version_label: ${{ github.run_id }}
        region: eu-north-1
        deployment_package: site.zip

    - name: ✅ Deployment successful
      run: echo "Deployment to AWS Elastic Beanstalk was successful!"
