name: Build, test and push to aws

on:
  push:
    branches:
      - main
      - dev  # Kan användas för VG, men är här för godkänd nivå också

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore cicdAPI.csproj  # Justera namnet på ditt projekt om det behövs

    - name: Build project
      run: dotnet build cicdAPI.csproj --configuration Release

    - name: Run tests
      run: dotnet test cicdAPI.csproj --configuration Release --no-build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Build and publish project
      run: |
        dotnet restore cicdAPI.csproj
        dotnet publish cicdAPI.csproj -c Release -f net9.0 -o site

    - name: Create zip package
      run: |
        cd site
        zip -r ../site.zip .

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: Cicd
        environment_name: Cicd-env
        version_label: ${{ github.run_id }}
        region: eu-north-1
        deployment_package: site.zip
