name: Build and Push to AWS

on:
  push:
    branches:
      - dev   # Körs när en push görs till dev-grenen
      - main  # Körs när en push görs till main-grenen
  pull_request:
    branches:
      - main  # Körs när en pull request görs mot main-grenen från dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Build project
      run: |
        dotnet restore
        dotnet publish -c Release -o site

    - name: Create zip package
      run: |
        cd site
        zip ../site.zip ./*
        cd ..

    - name: Deploy to AWS Elastic Beanstalk
      uses: aws-actions/aws-elastic-beanstalk-deploy@v1
      with:
        application-name: cicdAPI
        environment-name: CicdAPI-env
        version-label: ${{ github.run_id }}
        region: eu-north-1
        deployment-package: site.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
